image bg classroom       = "images/classroom.avif"
image bg library         = "images/bg_library.webp"
image bg school_corridor = "images/bg_school_corridor.webp"
image bg mc_room         = "images/bg_mc_room.jpg"
image bg classroom_desk  = "images/bg_classroom_desk.jpeg"

image mcneutral    = "images/BBG/mcneutral.png"
image mcsmile      = "images/BBG/mcsmile.png"
image mctalk       = "images/BBG/mctalk.png"
image mcmad        = "images/BBG/mcmad.png"
image mcdisturbed  = "images/BBG/mcdisturbed.png"
image mctears      = "images/BBG/mcintears.png"
image mctear       = "images/BBG/mctear.png"

image orionneutral   = "images/Black haired blue eye boy/orionquiet.png"
image orionsmile     = "images/Black haired blue eye boy/orionsmile.png"
image orioncalm      = "images/Black haired blue eye boy/orioncalmtalk.png"
image oriontalk      = "images/Black haired blue eye boy/orioncalmtalk.png"
image orionangry     = "images/Black haired blue eye boy/orionangrytalk.png"
image orionhugesmile = "images/Black haired blue eye boy/orionhugesmiletalk.png"
image oriondisturbed = "images/Black haired blue eye boy/oriondisturbed.png"
image orionsad       = "images/Black haired blue eye boy/orionsadquiet.png"
image orionsweat     = "images/Black haired blue eye boy/orionsweat.png"
image orioncrying    = "images/Black haired blue eye boy/orioncrying.png"
image oriontear      = "images/Black haired blue eye boy/oriontear.png"
